[env:UWBDevice_Rewrite]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 9600
build_flags=
  -DARDUINO_USB_CDC_ON_BOOT=1
  -std=c++14
lib_deps =
    https://github.com/F-Army/arduino-dw1000-ng.git@0.1.0
    hideakitai/ArduinoEigen@^0.2.0
    